/**
 * Prisma Seed Script - GDP Actions & Templates
 * Exécution: npx prisma db seed
 */

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function seedGDPActions() {
  console.log('📊 Seeding GDP Actions...')

  const gdpActions = [
    {
      standardType: 'GDP',
      actionCode: 'gdp-qs-1',
      title: 'Création du Manuel Qualité GDP',
      description: 'Rédiger un manuel qualité conforme aux exigences GDP.',
      requirementRef: 'quality-system',
      chapterNumber: 'quality-system',
      estimatedHours: 24,
      priorityWeight: 10,
      category: 'documentation',
      sectorVariations: { deliverables: ['Manuel Qualité GDP', 'Procédures associées'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 1,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-qs-2',
      title: 'Désignation du Pharmacien Responsable',
      description: 'Formaliser la désignation et les responsabilités du PR.',
      requirementRef: 'quality-system',
      chapterNumber: 'quality-system',
      estimatedHours: 4,
      priorityWeight: 10,
      category: 'management',
      sectorVariations: { deliverables: ['Lettre de mission PR', 'Délégations documentées'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 2,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-per-1',
      title: 'Plan de formation GDP',
      description: 'Établir un programme de formation initiale et continue GDP.',
      requirementRef: 'personnel',
      chapterNumber: 'personnel',
      estimatedHours: 16,
      priorityWeight: 10,
      category: 'training',
      sectorVariations: { deliverables: ['Plan de formation GDP', 'Supports de formation', 'Évaluations'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 3,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-per-2',
      title: 'Fiches de poste GDP',
      description: 'Créer les fiches de poste incluant les responsabilités GDP.',
      requirementRef: 'personnel',
      chapterNumber: 'personnel',
      estimatedHours: 8,
      priorityWeight: 7,
      category: 'documentation',
      sectorVariations: { deliverables: ['Fiches de poste', 'Organigramme'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 4,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-prem-1',
      title: 'Qualification thermique des zones de stockage',
      description: 'Réaliser le mapping thermique et qualifier les zones.',
      requirementRef: 'premises',
      chapterNumber: 'premises',
      estimatedHours: 40,
      priorityWeight: 10,
      category: 'infrastructure',
      sectorVariations: { deliverables: ['Rapport de mapping', 'Protocole de qualification', 'PV de qualification'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 5,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-prem-2',
      title: 'Système de monitoring température',
      description: 'Installer un système de surveillance continue avec alertes.',
      requirementRef: 'premises',
      chapterNumber: 'premises',
      estimatedHours: 24,
      priorityWeight: 10,
      category: 'infrastructure',
      sectorVariations: { deliverables: ['Système installé', 'Procédure de surveillance', "Seuils d'alerte"], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 6,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-prem-3',
      title: 'Sécurisation des accès',
      description: "Mettre en place un contrôle d'accès aux zones de stockage.",
      requirementRef: 'premises',
      chapterNumber: 'premises',
      estimatedHours: 16,
      priorityWeight: 7,
      category: 'infrastructure',
      sectorVariations: { deliverables: ["Système d'accès", 'Registre des autorisations'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 7,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-doc-1',
      title: 'Système de gestion documentaire GDP',
      description: 'Mettre en place la maîtrise des documents GDP.',
      requirementRef: 'documentation',
      chapterNumber: 'documentation',
      estimatedHours: 12,
      priorityWeight: 7,
      category: 'infrastructure',
      sectorVariations: { deliverables: ['Procédure documentaire', 'Liste des documents maîtrisés'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 8,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-ops-1',
      title: 'Procédure de qualification fournisseurs',
      description: 'Établir le processus de qualification des fournisseurs GDP.',
      requirementRef: 'operations',
      chapterNumber: 'operations',
      estimatedHours: 16,
      priorityWeight: 10,
      category: 'process',
      sectorVariations: { deliverables: ['Procédure qualification', "Questionnaire d'audit", 'Registre fournisseurs'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 9,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-ops-2',
      title: 'Procédure de réception',
      description: 'Formaliser les contrôles à réception des produits.',
      requirementRef: 'operations',
      chapterNumber: 'operations',
      estimatedHours: 8,
      priorityWeight: 10,
      category: 'process',
      sectorVariations: { deliverables: ['Procédure réception', 'Checklist de contrôle'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 10,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-ops-3',
      title: 'Gestion FEFO/FIFO',
      description: 'Mettre en place la gestion des péremptions.',
      requirementRef: 'operations',
      chapterNumber: 'operations',
      estimatedHours: 8,
      priorityWeight: 7,
      category: 'process',
      sectorVariations: { deliverables: ['Procédure FEFO', 'Paramétrage WMS'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 11,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-ops-4',
      title: 'Procédure de gestion des retours',
      description: 'Formaliser le processus de traitement des retours.',
      requirementRef: 'operations',
      chapterNumber: 'operations',
      estimatedHours: 8,
      priorityWeight: 7,
      category: 'process',
      sectorVariations: { deliverables: ['Procédure retours', 'Zone de quarantaine'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 12,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-comp-1',
      title: 'Procédure de gestion des réclamations',
      description: 'Créer le processus de traitement des réclamations.',
      requirementRef: 'complaints',
      chapterNumber: 'complaints',
      estimatedHours: 8,
      priorityWeight: 7,
      category: 'process',
      sectorVariations: { deliverables: ['Procédure réclamations', 'Formulaire de réclamation'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 13,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-comp-2',
      title: 'Procédure produits falsifiés',
      description: 'Établir le processus de détection des produits suspects.',
      requirementRef: 'complaints',
      chapterNumber: 'complaints',
      estimatedHours: 8,
      priorityWeight: 10,
      category: 'process',
      sectorVariations: { deliverables: ['Procédure falsification', 'Formation équipe'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 14,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-trans-1',
      title: 'Qualification des transporteurs',
      description: 'Qualifier les prestataires de transport GDP.',
      requirementRef: 'transport',
      chapterNumber: 'transport',
      estimatedHours: 24,
      priorityWeight: 10,
      category: 'process',
      sectorVariations: { deliverables: ['Questionnaire qualification', 'Accords qualité', 'Audits'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 15,
    },
    {
      standardType: 'GDP',
      actionCode: 'gdp-trans-2',
      title: 'Qualification des emballages',
      description: "Valider les solutions d'emballage pour la chaîne du froid.",
      requirementRef: 'transport',
      chapterNumber: 'transport',
      estimatedHours: 32,
      priorityWeight: 10,
      category: 'infrastructure',
      sectorVariations: { deliverables: ['Études de qualification', 'Profils thermiques', 'Choix emballages'], tips: [] },
      templateIds: [],
      dependsOnActions: [],
      displayOrder: 16,
    },
  ]

  for (const action of gdpActions) {
    await prisma.action.upsert({
      where: { actionCode: action.actionCode },
      update: action,
      create: action,
    })
  }

  console.log(`✅ ${gdpActions.length} actions GDP insérées`)
}

async function seedGDPTemplates() {
  console.log('📚 Seeding GDP Templates...')

  const gdpTemplates = [
    {
      standardType: 'GDP',
      templateCode: 'gdp-manuel-qualite',
      title: 'Manuel Qualité GDP',
      description: 'Manuel qualité conforme aux Bonnes Pratiques de Distribution.',
      category: 'manuel',
      fileFormat: 'docx',
      fileUrl: 'https://placeholder.com/gdp-manuel-qualite.docx',
      fileSize: 0,
      requirementRef: null,
      sectorAdaptations: { tags: ['obligatoire', 'pharmacien responsable'], estimatedCompletionHours: 24 },
      relatedActionCodes: [],
      downloadCount: 0,
      displayOrder: 1,
      isActive: true,
    },
    {
      standardType: 'GDP',
      templateCode: 'gdp-programme-surete',
      title: 'Programme de Sûreté Supply Chain',
      description: "Programme de sécurisation de la chaîne d'approvisionnement.",
      category: 'manuel',
      fileFormat: 'docx',
      fileUrl: 'https://placeholder.com/gdp-programme-surete.docx',
      fileSize: 0,
      requirementRef: null,
      sectorAdaptations: { tags: ['sûreté', 'falsification'], estimatedCompletionHours: 12 },
      relatedActionCodes: [],
      downloadCount: 0,
      displayOrder: 2,
      isActive: true,
    },
    {
      standardType: 'GDP',
      templateCode: 'gdp-procedure-reception',
      title: 'Procédure Réception',
      description: 'Procédure de contrôle à réception des produits pharmaceutiques.',
      category: 'procedure',
      fileFormat: 'docx',
      fileUrl: 'https://placeholder.com/gdp-procedure-reception.docx',
      fileSize: 0,
      requirementRef: 'operations',
      sectorAdaptations: { tags: ['réception', 'contrôle'], estimatedCompletionHours: 6 },
      relatedActionCodes: [],
      downloadCount: 0,
      displayOrder: 3,
      isActive: true,
    },
    {
      standardType: 'GDP',
      templateCode: 'gdp-procedure-stockage',
      title: 'Procédure Stockage',
      description: 'Procédure de stockage et conditions de conservation.',
      category: 'procedure',
      fileFormat: 'docx',
      fileUrl: 'https://placeholder.com/gdp-procedure-stockage.docx',
      fileSize: 0,
      requirementRef: 'premises',
      sectorAdaptations: { tags: ['stockage', 'température'], estimatedCompletionHours: 6 },
      relatedActionCodes: [],
      downloadCount: 0,
      displayOrder: 4,
      isActive: true,
    },
    {
      standardType: 'GDP',
      templateCode: 'gdp-procedure-expedition',
      title: 'Procédure Expédition',
      description: 'Procédure de préparation et expédition des commandes.',
      category: 'procedure',
      fileFormat: 'docx',
      fileUrl: 'https://placeholder.com/gdp-procedure-expedition.docx',
      fileSize: 0,
      requirementRef: 'operations',
      sectorAdaptations: { tags: ['expédition', 'livraison'], estimatedCompletionHours: 6 },
      relatedActionCodes: [],
      downloadCount: 0,
      displayOrder: 5,
      isActive: true,
    },
    {
      standardType: 'GDP',
      templateCode: 'gdp-procedure-retours',
      title: 'Procédure Retours',
      description: 'Procédure de gestion des retours clients.',
      category: 'procedure',
      fileFormat: 'docx',
      fileUrl: 'https://placeholder.com/gdp-procedure-retours.docx',
      fileSize: 0,
      requirementRef: 'operations',
      sectorAdaptations: { tags: ['retours', 'quarantaine'], estimatedCompletionHours: 4 },
      relatedActionCodes: [],
      downloadCount: 0,
      displayOrder: 6,
      isActive: true,
    },
    {
      standardType: 'GDP',
      templateCode: 'gdp-procedure-rappel',
      title: 'Procédure Rappel de Lots',
      description: 'Procédure de rappel de lots et retrait du marché.',
      category: 'procedure',
      fileFormat: 'docx',
      fileUrl: 'https://placeholder.com/gdp-procedure-rappel.docx',
      fileSize: 0,
      requirementRef: null,
      sectorAdaptations: { tags: ['rappel', 'vigilance'], estimatedCompletionHours: 6 },
      relatedActionCodes: [],
      downloadCount: 0,
      displayOrder: 7,
      isActive: true,
    },
    {
      standardType: 'GDP',
      templateCode: 'gdp-procedure-falsification',
      title: 'Procédure Produits Falsifiés',
      description: 'Procédure de détection des produits suspects/falsifiés.',
      category: 'procedure',
      fileFormat: 'docx',
      fileUrl: 'https://placeholder.com/gdp-procedure-falsification.docx',
      fileSize: 0,
      requirementRef: 'complaints',
      sectorAdaptations: { tags: ['falsification', 'sûreté'], estimatedCompletionHours: 6 },
      relatedActionCodes: [],
      downloadCount: 0,
      displayOrder: 8,
      isActive: true,
    },
    {
      standardType: 'GDP',
      templateCode: 'gdp-fiche-reception',
      title: 'Fiche Contrôle Réception',
      description: 'Checklist de contrôle à réception.',
      category: 'formulaire',
      fileFormat: 'docx',
      fileUrl: 'https://placeholder.com/gdp-fiche-reception.docx',
      fileSize: 0,
      requirementRef: null,
      sectorAdaptations: { tags: ['enregistrement', 'réception'], estimatedCompletionHours: 1 },
      relatedActionCodes: [],
      downloadCount: 0,
      displayOrder: 9,
      isActive: true,
    },
    {
      standardType: 'GDP',
      templateCode: 'gdp-fiche-deviation',
      title: 'Fiche Déviation Température',
      description: "Formulaire de déclaration d'excursion thermique.",
      category: 'formulaire',
      fileFormat: 'docx',
      fileUrl: 'https://placeholder.com/gdp-fiche-deviation.docx',
      fileSize: 0,
      requirementRef: null,
      sectorAdaptations: { tags: ['température', 'déviation'], estimatedCompletionHours: 1 },
      relatedActionCodes: [],
      downloadCount: 0,
      displayOrder: 10,
      isActive: true,
    },
    {
      standardType: 'GDP',
      templateCode: 'gdp-questionnaire-transporteur',
      title: 'Questionnaire Qualification Transporteur',
      description: "Questionnaire d'évaluation des transporteurs.",
      category: 'formulaire',
      fileFormat: 'docx',
      fileUrl: 'https://placeholder.com/gdp-questionnaire-transporteur.docx',
      fileSize: 0,
      requirementRef: 'transport',
      sectorAdaptations: { tags: ['transporteur', 'qualification'], estimatedCompletionHours: 2 },
      relatedActionCodes: [],
      downloadCount: 0,
      displayOrder: 11,
      isActive: true,
    },
    {
      standardType: 'GDP',
      templateCode: 'gdp-mapping-thermique',
      title: 'Protocole Mapping Thermique',
      description: 'Protocole de cartographie thermique des zones de stockage.',
      category: 'outil',
      fileFormat: 'docx',
      fileUrl: 'https://placeholder.com/gdp-mapping-thermique.docx',
      fileSize: 0,
      requirementRef: 'premises',
      sectorAdaptations: { tags: ['qualification', 'température'], estimatedCompletionHours: 8 },
      relatedActionCodes: [],
      downloadCount: 0,
      displayOrder: 12,
      isActive: true,
    },
    {
      standardType: 'GDP',
      templateCode: 'gdp-plan-formation',
      title: 'Plan de Formation GDP',
      description: 'Template de plan de formation aux BPD.',
      category: 'outil',
      fileFormat: 'xlsx',
      fileUrl: 'https://placeholder.com/gdp-plan-formation.xlsx',
      fileSize: 0,
      requirementRef: 'personnel',
      sectorAdaptations: { tags: ['formation', 'RH'], estimatedCompletionHours: 4 },
      relatedActionCodes: [],
      downloadCount: 0,
      displayOrder: 13,
      isActive: true,
    },
  ]

  for (const template of gdpTemplates) {
    await prisma.template.upsert({
      where: { templateCode: template.templateCode },
      update: template,
      create: template,
    })
  }

  console.log(`✅ ${gdpTemplates.length} templates GDP insérés`)
}

async function main() {
  console.log('\n🚀 Démarrage du seed Prisma...\n')
  console.log('================================================\n')

  try {
    await seedGDPActions()
    await seedGDPTemplates()

    console.log('\n================================================')
    console.log('✅ Seed terminé avec succès!')
    console.log('   - 16 actions GDP')
    console.log('   - 13 templates GDP\n')
  } catch (error) {
    console.error('❌ Erreur lors du seed:', error)
    throw error
  } finally {
    await prisma.$disconnect()
  }
}

main()
